# Generated by Django 5.0.4 on 2024-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='services/', verbose_name='Rasmi')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('about', models.TextField(verbose_name='Service haqida')),
            ],
            options={
                'verbose_name': 'Xizmatlar',
                'verbose_name_plural': 'Xizmatlar',
                'db_table': 'Service_Page',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='status',
            field=models.CharField(choices=[('deactive', 'deactive'), ('active', 'active')], default='deactive', max_length=255, verbose_name='Kurs holati'),
        ),
    ]
