# Generated by Django 5.0.4 on 2024-05-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_servicepage_alter_coursepage_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Why_Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='why/')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name': 'Why_Choose',
                'verbose_name_plural': 'Why_Choose',
                'db_table': 'Why_Choose',
                'managed': True,
            },
        ),
    ]
