# Generated by Django 5.0.4 on 2024-05-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_customer_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_reviews',
            options={'managed': True, 'verbose_name': 'MIjozlar fikri', 'verbose_name_plural': 'MIjozlar fikri'},
        ),
        migrations.AlterModelTable(
            name='customer_reviews',
            table='Customer_Reviews',
        ),
    ]
